name: "test"

on: push

jobs:
  test:
    name: "Unit tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm eslint
        run: npm run eslint

      - name: npm stylelint
        run: npm run stylelint

      - name: npm test
        run: npm test
